# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer

import warnings
warnings.filterwarnings('ignore')

In [5]:
import sys
print(sys.executable)

C:\Users\bhima\anaconda3\python.exe

In [2]:
import os
os.listdir(os.getcwd())

['.ipynb_checkpoints',
 'DataPreprocessing Practice.ipynb',
 'hotel_bookings.csv']

In [4]:
# ANSI Escape Codes for BOLD and Resetting formatting - to be used in print() method ..

B = "\033[1m"
R = "\033[0m"

In [5]:
# To avoid the data read error for UTF and other formats ..
import chardet

with open("hotel_bookings.csv", 'rb') as f:
    raw_data = f.read()
    result = chardet.detect(raw_data)
    detected_encoding = result['encoding']
    print(f"Detected encoding: {B}{detected_encoding}{R}")

Detected encoding: ascii

In [6]:
data = pd.read_csv("hotel_bookings.csv", encoding = detected_encoding)
print("Dataset has been read successfully.")

Dataset has been read successfully.

In [7]:
data.sample(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
53856,City Hotel,1,179,2016,July,27,1,0,2,2,...,Non Refund,1.0,NaN,0,Transient,65.0,0,0,Canceled,2016-05-10
19375,Resort Hotel,1,79,2016,February,8,18,2,3,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,0,Canceled,2015-12-16
55336,City Hotel,1,156,2016,August,33,11,0,1,2,...,No Deposit,9.0,NaN,0,Transient,103.5,0,0,Canceled,2016-03-08
97726,City Hotel,0,25,2016,September,38,16,2,2,2,...,No Deposit,9.0,NaN,0,Transient,154.0,0,0,Check-Out,2016-09-20
64239,City Hotel,1,16,2017,March,9,2,2,3,2,...,No Deposit,9.0,NaN,0,Transient,91.8,0,0,Canceled,2017-02-15
105975,City Hotel,0,70,2017,February,7,15,0,4,3,...,No Deposit,NaN,242.0,0,Transient-Party,108.0,0,0,Check-Out,2017-02-19
11228,Resort Hotel,1,5,2017,April,17,29,2,1,2,...,No Deposit,385.0,NaN,0,Transient-Party,26.0,0,0,Canceled,2017-04-24
12262,Resort Hotel,1,320,2017,June,25,20,2,8,2,...,No Deposit,240.0,NaN,0,Transient,135.9,0,1,Canceled,2016-09-09
78178,City Hotel,1,93,2015,December,52,26,2,1,2,...,No Deposit,9.0,NaN,0,Contract,106.2,0,1,Canceled,2015-10-05
13574,Resort Hotel,1,190,2017,August,34,20,2,4,2,...,No Deposit,240.0,NaN,0,Transient,230.0,0,0,Canceled,2017-02-18

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [9]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [12]:
data.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [14]:
print(f"\nSummary of percentage of {B}NULL values{R} found in the features :\n")
for col in data.columns:
    null_percentage = round((data[col].isnull().sum()/len(data) * 100), 2)
    if null_percentage > 0:
        print(f"{col:<10} : {B}{null_percentage} %{R}")

Summary of percentage of NULL values found in the features :

country    : 0.41 %
agent      : 13.69 %
company    : 94.31 %

### Handling Missing Values

There are multiple ways to handle missing values such as dropna and fillna in Pandas. But now we shall deal missing values using Imputer Technique. Such as:
 - Replace with `Mean`
 - Replace with `Median`
 - Replace with `Constant`
 - Replace with `Most Frequent`